spring:
  datasource:
    username: root
    password: Jia5201314
    url: jdbc:mysql://127.0.0.1:3306/big-gun?useUnicode=true&amp;zeroDateTimeBehavior=convertToNull&amp;useServerPrepStmts=false&amp;characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
#    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计，'wall'用于防火墙
#    filters: stat,wall,log4j
#    tomcat:
#      #最大活跃数
#      max-active: 20
#      #初始化数量
#      initial-size: 1
#      #最大连接等待时间
#      max-wait: 60000
#      #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
#      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#      min-idle: 1
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      validation-query: select 1 from dual
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#    dbcp2:
#      #打开PSCache,并且指定每个链接PSCache的大小
#      pool-prepared-statements: true
    #使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource

  jpa:
    show-sql: true
    database: MySQL
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: jsp