spring:
  datasource:
    username: root
    password: Jia5201314
    url: jdbc:mysql://127.0.0.1:3306/big-gun?useUnicode=true&amp;zeroDateTimeBehavior=convertToNull&amp;useServerPrepStmts=false&amp;characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    database: MySQL
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy